name: magic_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  encrypt: ^5.0.1
  dart_jsonwebtoken: ^2.5.0
  equatable: ^2.0.5
  logger: ^1.1.0
  mongo_dart: ^0.8.0
  uuid: ^3.0.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
